steps:
# Deploy for SSG
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/slide4vr-ssg', '-f', 'ssg/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/slide4vr-ssg']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'slide4vr-ssg', '--image', 'gcr.io/$PROJECT_ID/slide4vr-ssg', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/slide4vr-ssg