steps:
- name: node
  entrypoint: yarn
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', "
    gcloud secrets versions access latest --secret=VUE_APP_API_BASE_URL|(read x;    echo VUE_APP_API_BASE_URL=$x     ) > .env.production && 
    gcloud secrets versions access latest --secret=VUE_APP_AUTH_API_DOMAIN|(read x; echo VUE_APP_AUTH_API_DOMAIN=$x  ) >> .env.production &&
    gcloud secrets versions access latest --secret=VUE_APP_AUTH_API_KEY|(read x;    echo VUE_APP_AUTH_API_KEY=$x     ) >> .env.production
    " ]
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '.env.production', 'gs://slide4vr.nklab.dev']
- name: node
  entrypoint: yarn
  args: ['run', 'prod-build']
  #- name: 'gcr.io/cloud-builders/gsutil'
  #  args: ['rm', "gs://slide4vr.nklab.dev/**"]
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-R', './dist/*', 'gs://slide4vr.nklab.dev']
