steps:
# Deploy for CDN
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: yarn
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', "
    echo API_BASE_URL=https://slide4vr-api-dnb6froqha-uc.a.run.app > .env && 
    gcloud secrets versions access latest --secret=VUE_APP_AUTH_API_DOMAIN|(read x; echo FIREBAE_AUTH_DOMAIN=$x  ) >> .env &&
    gcloud secrets versions access latest --secret=VUE_APP_AUTH_API_KEY|(read x;    echo FIREBAE_AUTH_API_KEY=$x     ) >> .env
    " ]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: gsutil
  args: ['cp', 'gs://stg-slide4vr.nklab.dev/ssg-pages.json', 'ssg/ssg-pages.json']  
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: yarn
  args: ['generate']
- name: 'gcr.io/slide2vr/slide4vr_ui-builder'
